export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const REMOVE_INGRIDIENT = 'REMOVE_INGRIDIENT';
export const INIT_INGRIDIENTS = 'INIT_INGRIDIENTS';
export const FETCH_INGRIDIENTS_FAILED = 'FETCH_INGRIDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_ORDERS_START = 'AUTH__ORDERS_START';
export const AUTH_ORDERS_SUCCESS = 'AUTH__ORDERS_SUCCESS';
export const AUTH_ORDERS_FAIL = 'AUTH__ORDERS_FAIL';
export const AUTH_ORDERS_LOGOUT = 'AUTH_ORDERS_LOGOUT';

export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
